version: "3.8"
services:

  mysql-service:
    image: mysql:latest
    container_name: mysql-db
    networks:
      - spring-boot-mysql-network
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
  web-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    env_file: ./.env
    environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/$MYSQL_DATABASE?createDatabaseIfNotExist=true
          SPRING_DATASOURCE_USERNAME: $MYSQLDB_USER
          SPRING_DATASOURCE_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    networks:
      - spring-boot-mysql-network
    depends_on:
      - mysql-service
networks:
  spring-boot-mysql-network:
    driver: bridge